# Generated by Django 2.1.2 on 2018-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMBDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('source_type', models.CharField(blank=True, choices=[('SMB', 'SMB')], max_length=3)),
                ('user_id', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('client_name', models.CharField(max_length=64)),
                ('server_name', models.CharField(max_length=64)),
                ('server_ip', models.GenericIPAddressField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
