# Generated by Django 2.1.2 on 2018-10-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smbdirectory',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
    ]
