# Generated by Django 2.0.7 on 2018-07-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='instance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom.Patient'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom.Series'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom.Study'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
