# Generated by Django 2.0.7 on 2018-07-24 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_auto_20180724_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_patient_uid', message='Digits only!')]),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
    ]
