# Generated by Django 2.0.7 on 2018-07-22 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_auto_20180722_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
    ]
