# Generated by Django 2.1.2 on 2018-10-31 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_smbdirectory_last_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_uid',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
    ]
