# Generated by Django 2.1.2 on 2018-10-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_smbdirectory_share_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smbdirectory',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='smbdirectory',
            name='server_ip',
        ),
        migrations.RemoveField(
            model_name='smbdirectory',
            name='source_type',
        ),
    ]
