# Generated by Django 2.0.7 on 2018-07-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_auto_20180722_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='family_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='given_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='instance',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Instance Number'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='path',
            field=models.CharField(max_length=500, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='series',
            name='number',
            field=models.IntegerField(verbose_name='Series Number'),
        ),
    ]
