# Generated by Django 2.0.7 on 2018-07-26 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_auto_20180724_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='file',
            field=models.FileField(blank=True, upload_to='dicom'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_uid',
            field=models.CharField(blank=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)*$', code='invalid_uid', message='Digits and dots only!')]),
        ),
    ]
