# Generated by Django 2.1.3 on 2018-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0003_auto_20181031_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='has_raw_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instance',
            name='is_anonymized',
            field=models.BooleanField(default=False),
        ),
    ]
