# Generated by Django 2.1.2 on 2018-10-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0004_auto_20181029_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smbdirectory',
            options={'verbose_name_plural': 'SMB Directories'},
        ),
    ]
