# Generated by Django 2.2 on 2019-04-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualInformationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram_bins', models.IntegerField()),
                ('value', models.FloatField()),
                ('is_self_score', models.BooleanField(default=False)),
                ('one_nifti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_scores', to='mri.NIfTI')),
                ('one_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_mutual_information_scores', to='mri.Scan')),
                ('second_nifti', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_scoress', to='mri.NIfTI')),
                ('second_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_information_scores', to='mri.Scan')),
            ],
        ),
    ]
