# Generated by Django 2.1.7 on 2019-03-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mri', '0006_auto_20190330_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualInformationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histogram_bins', models.IntegerField()),
                ('value', models.FloatField()),
                ('first_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_mutual_information_scores', to='mri.Scan')),
                ('second_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_information_scores', to='mri.Scan')),
            ],
        ),
    ]
