# Generated by Django 2.1.7 on 2019-03-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_information', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualinformationscore',
            old_name='first_scan',
            new_name='one_scan',
        ),
    ]
