# Generated by Django 2.1.7 on 2019-04-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0007_auto_20190402_1444'),
        ('mutual_information', '0002_auto_20190331_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualinformationscore',
            name='is_self_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mutualinformationscore',
            name='one_nifti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_scores', to='mri.NIfTI'),
        ),
        migrations.AddField(
            model_name='mutualinformationscore',
            name='second_nifti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_scoress', to='mri.NIfTI'),
        ),
    ]
