from research.views.data_acquisition import DataAcquisitionViewSet
from research.views.event import EventViewSet
from research.views.group import GroupViewSet
from research.views.measurement_definition import MeasurementDefinitionViewSet
from research.views.procedure import ProcedureViewSet
from research.views.procedure_step import ProcedureStepViewSet
from research.views.study import StudyViewSet
from research.views.subject import SubjectViewSet
from research.views.task import TaskViewSet
