"""
Log messages for the :mod:`~accounts.models` module.
"""

SSH_KEY_QUERY_START: str = "Querying known hosts for export destination at {ip}..."
SSH_KEY_QUERY_FAILURE: str = "IP address {ip} is not identified as a known host."
SSH_KEY_QUERY_SUCCESS: str = "Public key ({key_name}) for IP address {ip} successfully retrieved."
SSH_KEY_VALIDATION_START: str = "Validating public key for host {ip}."
SSH_KEY_VALIDATION_FAILURE: str = "Host {ip} has unmatching public keys!\nExpected:\t{expected_name}\nReceived:\t{name}"
SSH_KEY_VALIDATION_SUCCESS: str = "Public key for host {ip} successfully validated."
SSH_KEY_VALIDATION_SKIP: str = "No registered public key found for {ip}, skipping key validation."
SSH_TRANSPORT_KEY: str = "SSH transport key encryption method to {ip} set to {key_name}."
SSH_TRANSPORT_INIT_START: str = "Initializing transport session to {export_destination}..."
SSH_TRANSPORT_INIT_FAILURE: str = "SSH Transport instance initialization failed with the following exception:\n{exception}"
SSH_TRANSPORT_INIT_SUCCESS: str = "SSH Transport instance to {export_destination} successfully initialized."
SSH_CONNECTION_START: str = "Initializing SSH client session to {export_destination}..."
SSH_CONNECTION_FAILURE: str = "SSH client session initialization to {export_destination} failed with the following exception:\n{exception}"
SSH_CONNECTION_SUCCESS: str = "SSH client session initialization to {export_destination} completed successfully."
SSH_HOST_KEY_QUERY_START: str = "Querying host {ip} public key..."
SSH_HOST_KEY_QUERY_FAILURE: str = "Failed to retrieve public key for IP address {ip} with the following exception:\n{exception}"
SSH_HOST_KEY_QUERY_SUCCESS: str = "Public key ({key_name}) for {ip} successfully retrieved."
SSH_PASSWORD_AUTH_START: str = "Attempting password authentication to {export_destination}..."
SSH_PASSWORD_AUTH_FAILURE: str = "Password authentication to {export_destination} failed with the following exception:\n{exception}"
SSH_PASSWORD_AUTH_SUCCESS: str = "Password authentication to {export_destination} successful."
SSH_TRANSPORT_ACTIVE: str = "Active SSH Transport instance found for {export_destination}."
SFTP_CLIENT_START: str = "Starting SFTP client connection to {export_destination}..."
SFTP_CLIENT_FAILURE: str = "Failed to start SFTP client connection to {export_destination} with the following exception:\n{exception}"
SFTP_CLIENT_SUCCESS: str = "SFTP client connection to {export_destination} successfully started."
SFTP_PUT_START: str = "Strating SFTP file transfer from {source} to {export_destination}:{destination}."
SFTP_PUT_FAILURE: str = "Failed to transfer {source} to {export_destination}:{destination} with the following exception:\n{exception}"
SFTP_PUT_SUCCESS: str = "Successfully copied {source} to {export_destination}:{destination}."
SFTP_PUT_EXISTS: str = "File already exists in {export_destination}:{destination}!"
SFTP_PUT_BAD_INPUT: str = "Bad put() source input type: {bad_type}! source may only be a Path instance, a string representing a path, or an iterable of either."
SFTP_PUT_ABORT: str = "Aborting file transfer from {source} to {export_destination}:{destination}."
SFTP_MKDIR_START: str = "Creating directory {path} within {export_destination}..."
SFTP_MKDIR_FAILURE: str = "Failed to create directory {path} within {export_destination} with the following exception:\n{exception}"
SFTP_MKDIR_SUCCESS: str = "Successfully create {path} within {export_destination}."
SFTP_MKDIR_EXISTS: str = "Path {path} already exists in {export_destination}!"

# flake8: noqa: E501
