version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    working_directory: ~/pylabber
    docker:
      - image: themattrix/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install tox
      - run:
          command: tox
          name: Test using tox

workflows:
  main:
    jobs:
      - build-and-test
