version: 2.1

orbs:
  python: circleci/python@0.3.0
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    working_directory: ~/pylabber
    docker:
      - image: themattrix/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_NAME: circle_test
          DB_USER: root
          DB_PASSWORD: password
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - run: apk update && apk add postgresql-dev
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install tox
      - run:
          command: tox
          name: Test using tox
      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  main:
    jobs:
      - build-and-test
