# Generated by Django 3.0.6 on 2020-07-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ('title',), 'verbose_name_plural': 'Laboratories'},
        ),
    ]
