# Generated by Django 2.1.3 on 2018-12-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_auto_20181203_1704")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        )
    ]
