# Generated by Django 3.2.6 on 2021-08-16 17:53

import mirage.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20201018_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportDestination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                ("ip", models.GenericIPAddressField(verbose_name="IP")),
                ("username", models.CharField(max_length=128)),
                ("password", mirage.fields.EncryptedCharField(max_length=128)),
                ("destination", models.CharField(max_length=512)),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={"abstract": False,},
        ),
    ]
