# Generated by Django 3.2.6 on 2021-11-26 17:58

from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_exportdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdestination',
            name='banner_timeout',
            field=models.PositiveIntegerField(default=100, help_text='Timeout for an SSH banner to be presented (seconds)'),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='negotiation_timeout',
            field=models.PositiveIntegerField(default=3, help_text='Timeout for SSH2 session negotiation (seconds)'),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='port',
            field=models.PositiveIntegerField(default=22, help_text='Port used for SSH2 transport session initialization'),
        ),
        migrations.AddField(
            model_name='exportdestination',
            name='socket_timeout',
            field=models.PositiveIntegerField(default=3, help_text='Timeout for socket creation (seconds)'),
        ),
        migrations.AlterField(
            model_name='exportdestination',
            name='destination',
            field=models.CharField(help_text='Base path on the host to use for relative file transfers', max_length=512),
        ),
        migrations.AlterField(
            model_name='exportdestination',
            name='ip',
            field=models.GenericIPAddressField(help_text='SSH server host IP address', verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='exportdestination',
            name='password',
            field=mirage.fields.EncryptedCharField(help_text='Password used for SSH authentication', max_length=128),
        ),
        migrations.AlterField(
            model_name='exportdestination',
            name='username',
            field=models.CharField(help_text='Username used for SSH authentication', max_length=128),
        ),
    ]
