# Generated by Django 2.1.5 on 2019-02-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190121_1734'),
        ('accounts', '0011_auto_20190102_0926'),
    ]

    operations = [
    ]
