# Generated by Django 2.1.7 on 2019-03-30 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mri.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0004_auto_20190330_1039'),
        ('django_dicom', '0004_auto_20190330_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=100)),
                ('echo_time', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('inversion_time', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('repetition_time', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dicom', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_dicom.Series')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('scanning_sequence', mri.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('SE', 'Spin Echo'), ('IR', 'Inversion Recovery'), ('GR', 'Gradient Recalled'), ('EP', 'Echo Planar'), ('RM', 'Research Mode')], max_length=2), blank=True, null=True, size=5)),
                ('sequence_variant', mri.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('SK', 'Segmented k-Space'), ('MTC', 'Magnetization Transfer Contrast'), ('SS', 'Steady State'), ('TRSS', 'Time Reversed Steady State'), ('SP', 'Spoiled'), ('MP', 'MAG Prepared'), ('OSP', 'Oversampling Phase'), ('NONE', 'None')], max_length=4), blank=True, null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='scan',
            name='sequence_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mri.SequenceType'),
        ),
        migrations.AddField(
            model_name='scan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research.Subject'),
        ),
    ]
