# Generated by Django 2.1.7 on 2019-03-30 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
