# Generated by Django 2.1.7 on 2019-03-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0002_auto_20190330_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='sequence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mri.SequenceType'),
        ),
        migrations.AlterField(
            model_name='sequencetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='sequencetype',
            unique_together={('scanning_sequence', 'sequence_variant')},
        ),
    ]
