# Generated by Django 2.1.7 on 2019-03-30 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0004_auto_20190330_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='spatial_resolution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 0, 0], size=3),
            preserve_default=False,
        ),
    ]
