# Generated by Django 2.1.7 on 2019-03-30 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0005_scan_spatial_resolution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('time',), 'verbose_name_plural': 'MRI Scans'},
        ),
        migrations.AlterField(
            model_name='scan',
            name='spatial_resolution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=3),
        ),
    ]
