# Generated by Django 2.1.7 on 2019-04-02 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mri', '0006_auto_20190330_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nifti',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='nifti',
            name='created_at',
        ),
        migrations.AddField(
            model_name='nifti',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nifti',
            name='is_raw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nifti',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='nifti',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_niftis', to='mri.Scan'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
