# Generated by Django 2.1 on 2018-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20180808_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options', to='questionnaires.Option'),
        ),
    ]
