# Generated by Django 2.1 on 2018-08-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(related_name='questionnaires', to='questionnaires.Questionnaire'),
        ),
    ]
