# Generated by Django 2.1 on 2018-08-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20180809_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionnaires.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(to='questionnaires.Questionnaire'),
        ),
    ]
