# Generated by Django 2.1 on 2018-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_auto_20180809_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(related_name='questions', to='questionnaires.Questionnaire'),
        ),
    ]
