# Generated by Django 2.1 on 2018-08-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_auto_20180809_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='options_for', to='questionnaires.Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_for', to='questionnaires.Option'),
        ),
    ]
