# Generated by Django 2.1 on 2018-08-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_auto_20180809_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='option_for', to='questionnaires.Option'),
        ),
    ]
