# Generated by Django 2.0.7 on 2018-07-24 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Studies',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('id_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')])),
                ('phone_number', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')])),
                ('dominant_hand', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('A', 'Ambidextrous')], default='R', max_length=1)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('C', 'Cisgender'), ('T', 'Transgender'), ('O', 'Other')], default='C', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='subjects',
            field=models.ManyToManyField(related_name='studies', to='research.Subject'),
        ),
    ]
