# Generated by Django 2.1 on 2018-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dominant_hand',
            field=models.CharField(blank=True, choices=[('RIGHT', 'Right'), ('LEFT', 'Left'), ('AMBI', 'Ambidextrous')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(blank=True, choices=[('CIS', 'Cisgender'), ('TRANS', 'Transgender'), ('OTHER', 'Other')], max_length=5),
        ),
    ]
