# Generated by Django 2.0.7 on 2018-07-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('id_number', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dominant_hand', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('A', 'Ambidextrous')], max_length=1)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('C', 'Cisgender'), ('T', 'Transgender'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
