# Generated by Django 2.2 on 2019-12-04 05:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='custom_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
