# Generated by Django 3.0.6 on 2020-09-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
            ],
            options={"ordering": ("title",),},
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
            ],
            options={"ordering": ("title",),},
        ),
        migrations.CreateModel(
            name="MeasurementDefinition",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="research.Event",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("research.event",),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="research.Event",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("research.event",),
        ),
        migrations.CreateModel(
            name="ProcedureStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.Event",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.Procedure",
                    ),
                ),
            ],
            options={
                "ordering": ("index",),
                "unique_together": ("procedure", "index"),
            },
        ),
        migrations.AddField(
            model_name="procedure",
            name="events",
            field=models.ManyToManyField(
                through="research.ProcedureStep", to="research.Event"
            ),
        ),
    ]
    # Added this part in order to control the models creation
    # (Session model is related to MeasurementDefinition in this case)
    run_before = [("django_mri", "0009_auto_20200929_0818")]
