# Generated by Django 2.2 on 2019-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dominant_hand',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left'), ('A', 'Ambidextrous')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(blank=True, choices=[('CIS', 'Cisgender'), ('TRANS', 'Transgender'), ('OTHER', 'Other')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Other')], max_length=6, null=True),
        ),
    ]
