# Generated by Django 2.2.12 on 2020-04-25 09:58

from django.db import migrations
import pylabber.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=pylabber.utils.utils.CharNullField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
