# Generated by Django 2.1.3 on 2018-11-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='phone_number',
        ),
    ]
