# Generated by Django 2.2 on 2019-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
