# Generated by Django 2.0.7 on 2018-07-24 13:39

from django.db import migrations, models
import research.models.choices


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180724_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(blank=True, choices=[('CIS', 'Cisgender'), ('TRANS', 'Transgender'), ('OTHER', 'Other')], default=research.models.choices.Gender('Cisgender'), max_length=5),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6),
        ),
    ]
