# Generated by Django 2.1 on 2018-08-08 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20180805_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='research.Subject'),
        ),
    ]
