# Generated by Django 3.1.2 on 2020-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20200927_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='procedurestep',
            unique_together={('procedure', 'index')},
        ),
    ]
