# Generated by Django 2.0.7 on 2018-07-20 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=models.CharField(blank=True, default='', max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_id_number', message='Digits only')]),
            preserve_default=False,
        ),
    ]
