# Generated by Django 3.1.3 on 2020-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20201018_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='study',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='research.Procedure'),
        ),
    ]
