# Generated by Django 2.0.7 on 2018-07-20 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180720_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='dominant_hand',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('A', 'Ambidextrous')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='gender',
            field=models.CharField(blank=True, choices=[('C', 'Cisgender'), ('T', 'Transgender'), ('O', 'Other')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_id_number', message='Digits only!')]),
        ),
    ]
