# Generated by Django 2.1 on 2018-08-09 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180808_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='collaborators',
            field=models.ManyToManyField(related_name='studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='study',
            name='subjects',
            field=models.ManyToManyField(related_name='studies', to='research.Subject'),
        ),
    ]
