# Generated by Django 3.1.3 on 2020-11-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20201018_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='study',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='research.procedure'),
        ),
    ]
