# Generated by Django 2.0.7 on 2018-07-20 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20180720_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='subject',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')]),
        ),
    ]
