# Generated by Django 3.1.3 on 2020-11-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20201115_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ('procedure', 'index')},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ('title',), 'verbose_name_plural': 'Studies'},
        ),
    ]
