# Generated by Django 2.0.7 on 2018-07-26 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20180724_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')]),
        ),
    ]
