# Generated by Django 3.1.3 on 2021-04-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('research', '0005_auto_20201122_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementdefinition',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='procedurestep',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='step_set', to='research.procedure'),
        ),
    ]
