# Generated by Django 2.0.7 on 2018-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20180720_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='subjects',
            field=models.ManyToManyField(to='research.Subject'),
        ),
    ]
