# Generated by Django 2.0.7 on 2018-07-27 09:24

import django.core.validators
from django.db import migrations, models
import research.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20180726_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[research.models.validators.not_future], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')]),
        ),
    ]
