# Generated by Django 2.0.7 on 2018-07-27 09:27

import django.core.validators
from django.db import migrations
import pylabber.utils


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20180727_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='id_number',
            field=pylabber.utils.CharNullField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', code='invalid_number', message='Digits only!')]),
        ),
    ]
